name: Deprecate Removed Scenarios

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deprecate-scenarios:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Compare feature files and find removed scenarios
        run: |
          echo "::group::Archivos cambiados"
          git diff --unified=0 HEAD^ HEAD --name-only -- '*.feature' > changed_files.txt
          cat changed_files.txt
          echo "::endgroup::"

          > removed_ids.txt

          while read -r file; do
            echo "::group:: Analyze file $file"
            echo "Showing complete diff:"
            git diff --unified=0 HEAD^ HEAD -- "$file"

            echo "Search removed lines:"
            git diff --unified=0 HEAD^ HEAD -- "$file" | grep '^-' > removed_lines.txt
            cat removed_lines.txt

            # Debug lines

            echo "DEBUG: Intentando búsqueda directa de QANOV:"
            cat removed_lines.txt | grep -F "QANOV" || echo "No se encontró QANOV"
            # Search for scenario tags in removed lines
            cat removed_lines.txt | grep -v '^---' | sed 's/^-//' | grep -Eo '(QANOV|QABP)-\d+' >> removed_ids.txt || echo "No removed scenarios detected in $file"

            echo "::endgroup::"
          done < changed_files.txt

          echo "IDs found:"
          cat removed_ids.txt

      - name: Annotate removed scenario IDs
        run: |
          if [ -s removed_ids.txt ]; then
            ids=$(paste -sd, - < removed_ids.txt)
            echo "::notice title=Removed scenarios::Detected IDs: $ids"
          else
            echo "No removed scenarios detected."
          fi
