name: Deprecate Removed Scenarios

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  detect-removed-scenarios:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Compare feature files and find removed scenarios
        run: |
          echo "::group::Archivos cambiados"
          git diff --unified=0 HEAD^ HEAD --name-only -- '*.feature' > changed_files.txt
          cat changed_files.txt
          echo "::endgroup::"

          > removed_ids.txt

          while read -r file; do
            echo "::group:: Analyze file $file"
            echo "Showing complete diff:"
            git diff --unified=0 HEAD^ HEAD -- "$file"

            echo "Search removed lines:"
            git diff --unified=0 HEAD^ HEAD -- "$file" | grep '^-' > removed_lines.txt
            cat removed_lines.txt

            # Search for scenario tags in removed lines
            cat removed_lines.txt | grep -Eo '(QANOV|QABP)-[0-9]+' >> removed_ids.txt

            echo "::endgroup::"
          done < changed_files.txt

          echo "IDs found:"
          cat removed_ids.txt

      - name: Annotate removed scenario IDs
        run: |
          if [ -s removed_ids.txt ]; then
            ids=$(paste -sd, - < removed_ids.txt)
            echo "::notice title=Removed scenarios::Detected IDs: $ids"
          else
            echo "No removed scenarios detected."
          fi

      - name: Read issues from file and output as json
        id: get-issues
        run: |
          issues=$(jq -R -s -c 'split("\n"))' removed_ids.txt)
          echo "issues=$issues" >> $GITHUB_OUTPUT

    outputs:
      issues: ${{ steps.get-issues.outputs.issues }}

  transition-scenarios:
    needs: detect-removed-scenarios
    runs-on: ubuntu-latest
    strategy:
      matrix:
        issue: ${{ fromJson(needs.detect-removed-scenarios.outputs.issues) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Transition Jira scenario to Deprecated
        uses: Telefonica/qacdonovum-github-actions/transition-jira-issue@0.3
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        with:
          issue: ${{ matrix.issue }}
          target_status: Deprecated