name: Deprecate Removed Scenarios

on:
  pull_request:
    types:
      - closed
    branches:
      - main


jobs:
  detect-removed-scenarios:
    if: github.event.pull_request.merged == true
    # For testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Compare feature files and find removed scenarios
        run: |
          echo "::group::Changed files"
          git diff --unified=0 HEAD^ HEAD --name-only -- '*.feature' > changed_files.txt
          cat changed_files.txt
          echo "::endgroup::"

          # Check if no feature files were changed
          if [ ! -s changed_files.txt ]; then
            echo "No feature files changed."
            echo "::notice title=No changes::No feature files were modified"
            exit 0
          fi

          > removed_ids.txt


          while read -r file; do
            echo "::group:: Analyze file $file"
            echo "Showing complete diff:"
            git diff --unified=0 HEAD^ HEAD -- "$file"

            echo "Search removed and added lines:"
            git diff --unified=0 HEAD^ HEAD -- "$file" | grep '^-'> removed_lines.txt || true
            git diff --unified=0 HEAD^ HEAD -- "$file" | grep '^+'> added_lines.txt || true
            cat removed_lines.txt
            cat added_lines.txt

            # Extract scenario tags from removed and added lines
            cat removed_lines.txt | grep -Eo '(QANOV|QABP)-[0-9]+' | sort | uniq > removed_ids_tmp.txt || true
            cat added_lines.txt | grep -Eo '(QANOV|QABP)-[0-9]+' | sort | uniq > added_ids_tmp.txt || true

            # Only keep IDs that are in removed but not in added
            comm -23 removed_ids_tmp.txt added_ids_tmp.txt >> removed_ids.txt || true

            echo "::endgroup::"
          done < changed_files.txt

          echo "IDs found:"
          cat removed_ids.txt || echo "No IDs found"

      - name: Annotate removed scenario IDs
        run: |
          if [ -s removed_ids.txt ]; then
            ids=$(paste -sd, - < removed_ids.txt)
            echo "::notice title=Removed scenarios::Detected IDs: $ids"
          else
            echo "No removed scenarios detected."
          fi

      - name: Read issues from file and output as json
        id: get-issues
        run: |
          if [ -s removed_ids.txt ]; then
            issues=$(jq -R -s -c 'split("\n")' removed_ids.txt)
            echo "issues=$issues" >> $GITHUB_OUTPUT
          else
            echo "issues=[]" >> $GITHUB_OUTPUT
          fi