name: Consulta de Jira

on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: 'Jira Issue Key'
        required: true

jobs:
  consultar-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar a la API de Jira
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          ISSUE_KEY: ${{ inputs.issue_key }}
        run: |
          curl -s -X GET \
            -H "Authorization: Bearer $JIRA_TOKEN" \
            -H "Content-Type: application/json" \
            "https://jira.tid.es/rest/api/3/issue/$ISSUE_KEY" \
            | jq '.fields.summary'
