name: Consulta de Jira

on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: 'Jira Issue Key'
        required: true

jobs:
  consultar-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar a la API de Jira
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          ISSUE_KEY: ${{ inputs.issue_key }}
        run: |
          echo "Conectando a Jira para consultar el ticket: $ISSUE_KEY"

          RESPONSE=$(curl -s -X GET \
            -H "Authorization: Bearer $JIRA_TOKEN" \
            -H "Content-Type: application/json" \
            "https://jira.tid.es/rest/api/3/issue/$ISSUE_KEY")

          if echo "$RESPONSE" | jq -e '.errorMessages' > /dev/null 2>&1; then
            echo "❌ Error al conectar con Jira:"
            echo "$RESPONSE" | jq '.errorMessages'
            exit 1
          else
            echo "✅ Conexión exitosa"
            echo "📋 Resumen del ticket:"
            echo "$RESPONSE" | jq -r '.fields.summary'
          fi
